# Generated by Django 3.2.19 on 2024-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_deletekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletetable',
            name='deletekey',
            field=models.CharField(default=False, max_length=140),
        ),
    ]
