# Generated by Django 3.2.19 on 2024-07-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_breakendtime_breakstarttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.TextField(),
        ),
    ]
